# Data Cleaning and Preprocessing

In [1]:
# Basic Libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
sb.set() # set the default Seaborn style for graphics

In [2]:
file_path = [
    'dataset/anime.csv',
    'dataset/rankings/ranking_airing.csv'
    # ADD the remaining ranking csv files here!!!
]

---

# Exploring and Cleaning `anime.csv` first

In [3]:
data = pd.read_csv(file_path[0])
pd.set_option('display.max_columns', None)
data.head(n=3)

,id,title,main_picture,start_date,end_date,synopsis,mean,rank,popularity,num_list_users,num_scoring_users,nsfw,created_at,updated_at,media_type,status,genres,num_episodes,start_season,broadcast,source,average_episode_duration,rating,background,studios,statistics
0,95,Turn A Gundam,{'medium': 'https://api-cdn.myanimelist.net/im...,1999-04-09,2000-04-14,"It is the Correct Century, two millennia after...",7.71,1049,2892,40743,13338,white,2005-11-11T13:54:05+00:00,2022-03-22T03:37:48+00:00,tv,finished_airing,"[{'id': 1, 'name': 'Action'}, {'id': 2, 'name'...",50,"{'year': 1999, 'season': 'spring'}","{'day_of_the_week': 'friday', 'start_time': '1...",original,1445,pg_13,NaN,"[{'id': 14, 'name': 'Sunrise'}, {'id': 1260, '...","{'status': {'watching': '2735', 'completed': '..."
1,3665,Ginga Eiyuu Densetsu Gaiden (1999),{'medium': 'https://api-cdn.myanimelist.net/im...,1999-12-24,2000-07-21,Ginga Eiyuu Densetsu Gaiden (1999) is the seco...,8.07,472,4347,17849,6478,white,2008-01-02T21:05:12+00:00,2022-03-18T19:39:11+00:00,ova,finished_airing,"[{'id': 1, 'name': 'Action'}, {'id': 8, 'name'...",28,"{'year': 1999, 'season': 'fall'}",NaN,novel,1560,r,NaN,"[{'id': 8, 'name': 'Artland'}, {'id': 207, 'na...","{'status': {'watching': '814', 'completed': '8..."
2,2471,Doraemon (1979),{'medium': 'https://api-cdn.myanimelist.net/im...,1979-04-02,2005-03-18,Nobita Nobi is a normal fourth grade student. ...,7.74,976,2553,51255,23826,white,2007-05-11T22:02:20+00:00,2022-03-23T06:24:35+00:00,tv,finished_airing,"[{'id': 2, 'name': 'Adventure'}, {'id': 4, 'na...",1787,"{'year': 1979, 'season': 'spring'}",NaN,manga,660,pg,NaN,"[{'id': 247, 'name': 'Shin-Ei Animation'}]","{'status': {'watching': '4637', 'completed': '..."

---

# 1. Handling missing values & Unused Features

In [4]:
# Check missing values in data
print("Missing values in dataframe:")
print(data.isnull().sum())
print("data shape: ", data.shape)

Missing values in dataframe:
id                             0
title                          0
main_picture                   0
start_date                     0
end_date                     876
synopsis                     128
mean                         116
rank                           0
popularity                     0
num_list_users                 0
num_scoring_users              0
nsfw                           0
created_at                     0
updated_at                     0
media_type                     0
status                         0
genres                         8
num_episodes                   0
start_season                   0
broadcast                   5372
source                       901
average_episode_duration       0
rating                        61
background                  7067
studios                        0
statistics                     0
dtype: int64
data shape:  (8777, 26)

## 1a. Dropping Unused Features

- We are dropping main_picture which is the profile picture of the anime, creat_date and update_date which is the create and update dates of the anime's MAL page, and background which is the background of the anime. 
- Because anime photo, site creation and update date does not provide useful information about the anime itself, and there are too many null values (7067/8777) for background.

In [5]:
# Drop columns: main_picture, created_at, updated_at, background
data_clean = data.drop(columns=['main_picture', 'created_at', 'updated_at', 'background'])
data_clean.head(n=3)

,id,title,start_date,end_date,synopsis,mean,rank,popularity,num_list_users,num_scoring_users,nsfw,media_type,status,genres,num_episodes,start_season,broadcast,source,average_episode_duration,rating,studios,statistics
0,95,Turn A Gundam,1999-04-09,2000-04-14,"It is the Correct Century, two millennia after...",7.71,1049,2892,40743,13338,white,tv,finished_airing,"[{'id': 1, 'name': 'Action'}, {'id': 2, 'name'...",50,"{'year': 1999, 'season': 'spring'}","{'day_of_the_week': 'friday', 'start_time': '1...",original,1445,pg_13,"[{'id': 14, 'name': 'Sunrise'}, {'id': 1260, '...","{'status': {'watching': '2735', 'completed': '..."
1,3665,Ginga Eiyuu Densetsu Gaiden (1999),1999-12-24,2000-07-21,Ginga Eiyuu Densetsu Gaiden (1999) is the seco...,8.07,472,4347,17849,6478,white,ova,finished_airing,"[{'id': 1, 'name': 'Action'}, {'id': 8, 'name'...",28,"{'year': 1999, 'season': 'fall'}",NaN,novel,1560,r,"[{'id': 8, 'name': 'Artland'}, {'id': 207, 'na...","{'status': {'watching': '814', 'completed': '8..."
2,2471,Doraemon (1979),1979-04-02,2005-03-18,Nobita Nobi is a normal fourth grade student. ...,7.74,976,2553,51255,23826,white,tv,finished_airing,"[{'id': 2, 'name': 'Adventure'}, {'id': 4, 'na...",1787,"{'year': 1979, 'season': 'spring'}",NaN,manga,660,pg,"[{'id': 247, 'name': 'Shin-Ei Animation'}]","{'status': {'watching': '4637', 'completed': '..."

In [6]:
data_clean.shape

(8777, 22)

## 1b. Filling in NaN values with domain-specific values

In [7]:
# No synopsis information available
data_clean["synopsis"].fillna(value = "no_Synopsis", inplace = True)

# Anime still airing/ongoing
data_clean["end_date"].fillna(value = "airing", inplace = True)

# Anime not broadcasted, replace missing value with the same formet for easy sorting
data_clean["broadcast"].fillna(value = "{'day_of_the_week': 'NIL', 'start_time': 'NIL'}", inplace = True)

# Source not known
data_clean["source"].fillna(value = "unknown", inplace = True)

# Not rated
data_clean["rating"].fillna(value = "no_rating", inplace = True)

# No genre information
data_clean["genres"].fillna(value = "[{'id': -1, 'name': 'no_genre'}]", inplace = True)

# Animes that do not have enough user giving their scorings, so replace null with value -1
data_clean["mean"].fillna(value = "-1", inplace = True)
#data_clean = data_clean[~np.isnan(data["mean"])]

# Check null values after cleaning
data_clean.isnull().sum()

id                          0
title                       0
start_date                  0
end_date                    0
synopsis                    0
mean                        0
rank                        0
popularity                  0
num_list_users              0
num_scoring_users           0
nsfw                        0
media_type                  0
status                      0
genres                      0
num_episodes                0
start_season                0
broadcast                   0
source                      0
average_episode_duration    0
rating                      0
studios                     0
statistics                  0
dtype: int64

In [8]:
data_clean.head()

,id,title,start_date,end_date,synopsis,mean,rank,popularity,num_list_users,num_scoring_users,nsfw,media_type,status,genres,num_episodes,start_season,broadcast,source,average_episode_duration,rating,studios,statistics
0,95,Turn A Gundam,1999-04-09,2000-04-14,"It is the Correct Century, two millennia after...",7.71,1049,2892,40743,13338,white,tv,finished_airing,"[{'id': 1, 'name': 'Action'}, {'id': 2, 'name'...",50,"{'year': 1999, 'season': 'spring'}","{'day_of_the_week': 'friday', 'start_time': '1...",original,1445,pg_13,"[{'id': 14, 'name': 'Sunrise'}, {'id': 1260, '...","{'status': {'watching': '2735', 'completed': '..."
1,3665,Ginga Eiyuu Densetsu Gaiden (1999),1999-12-24,2000-07-21,Ginga Eiyuu Densetsu Gaiden (1999) is the seco...,8.07,472,4347,17849,6478,white,ova,finished_airing,"[{'id': 1, 'name': 'Action'}, {'id': 8, 'name'...",28,"{'year': 1999, 'season': 'fall'}","{'day_of_the_week': 'NIL', 'start_time': 'NIL'}",novel,1560,r,"[{'id': 8, 'name': 'Artland'}, {'id': 207, 'na...","{'status': {'watching': '814', 'completed': '8..."
2,2471,Doraemon (1979),1979-04-02,2005-03-18,Nobita Nobi is a normal fourth grade student. ...,7.74,976,2553,51255,23826,white,tv,finished_airing,"[{'id': 2, 'name': 'Adventure'}, {'id': 4, 'na...",1787,"{'year': 1979, 'season': 'spring'}","{'day_of_the_week': 'NIL', 'start_time': 'NIL'}",manga,660,pg,"[{'id': 247, 'name': 'Shin-Ei Animation'}]","{'status': {'watching': '4637', 'completed': '..."
3,21,One Piece,1999-10-20,airing,"Gol D. Roger was known as the ""Pirate King,"" t...",8.63,66,26,1812581,1020274,white,tv,currently_airing,"[{'id': 1, 'name': 'Action'}, {'id': 2, 'name'...",0,"{'year': 1999, 'season': 'fall'}","{'day_of_the_week': 'sunday', 'start_time': '0...",manga,1440,pg_13,"[{'id': 18, 'name': 'Toei Animation'}]","{'status': {'watching': '1227452', 'completed'..."
4,2397,Digimon Adventure: Bokura no War Game!,2000-03-04,2000-03-04,This movie takes place after the Adventure ser...,7.77,924,2135,70125,43599,white,movie,finished_airing,"[{'id': 2, 'name': 'Adventure'}, {'id': 4, 'na...",1,"{'year': 2000, 'season': 'winter'}","{'day_of_the_week': 'NIL', 'start_time': 'NIL'}",original,2460,pg,"[{'id': 18, 'name': 'Toei Animation'}]","{'status': {'watching': '653', 'completed': '6..."

---


# 2. Cleaning features by converting into json and splitting into different columns

In [9]:
# Import library for json manipulation
import json

In [10]:
# Splitting start_season column into individual year and season columns
def split_start_season(data_clean):
    # create NaN columns
    data_clean['start_season_year'] = np.nan
    data_clean['start_season_season'] = np.nan

    
    for row in range(0,len(data_clean)):
        #convert from string to json
        start_season = (json.loads(data_clean['start_season'][row].replace("'", "\"")))
        year = start_season['year']
        season = start_season['season']

        data_clean['start_season_year'][row] = year
        data_clean['start_season_season'][row] = season
    
    
    # drop original column
    data_clean.drop(columns=['start_season'], inplace=True)
    
    
    return data_clean

In [11]:
# Splitting broadcast column into individual day and time columns
def split_broadcast(data_clean):
    # create NaN columns
    data_clean['broadcast_day_of_the_week'] = np.nan
    data_clean['broadcast_start_time'] = np.nan

    
    for row in range(0,len(data_clean)):
        #convert from string to json
        broadcast = (json.loads(data_clean['broadcast'][row].replace("'", "\"")))


        data_clean['broadcast_day_of_the_week'][row] = broadcast['day_of_the_week']

        try:
            data_clean['broadcast_start_time'][row] = broadcast['start_time']
        except:
            data_clean['broadcast_start_time'][row] = 'NIL'
    
    
    # drop original column
    data_clean.drop(columns=['broadcast'], inplace=True)
    
    
    return data_clean

In [12]:
# Splitting statistics column into watching, completed, on hold, plan to watch and num of user columns

def split_statistics(data_clean):
    # create NaN columns
    data_clean['statistics_watching'] = np.nan
    data_clean['statistics_completed'] = np.nan
    data_clean['statistics_on_hold'] = np.nan
    data_clean['statistics_dropped'] = np.nan
    data_clean['statistics_plan_to_watch'] = np.nan
    data_clean['statistics_num_list_users'] = np.nan


    for row in range(0,len(data_clean)):
        # convert from string to json
        statistics = (json.loads(data_clean['statistics'][row].replace("'", "\"")))

        data_clean['statistics_watching'][row] = statistics['status']['watching']
        data_clean['statistics_completed'][row] = statistics['status']['completed']
        data_clean['statistics_on_hold'][row] = statistics['status']['on_hold']
        data_clean['statistics_dropped'][row] = statistics['status']['dropped']
        data_clean['statistics_plan_to_watch'][row] = statistics['status']['plan_to_watch']
        data_clean['statistics_num_list_users'][row] = statistics['num_list_users']
    
    
    # drop original column
    data_clean.drop(columns=['statistics'], inplace=True)
    
    
    return data_clean

In [13]:
# Convert studios into json format
def json_studios(data_clean):
    # Convert studios string to json
    for row in range(0, len(data_clean)):
        try:
            studios = (json.loads(data_clean['studios'][row].replace("'", "\"")))
        except:
            studios = (json.loads(data_clean['studios'][row].replace("'", "\"").replace("\"s", '\'s').replace('N\"', "N\'")))

        data_clean['studios'][row] = studios
    
    return data_clean

In [14]:
# Convert genres into json format
def json_genres(data_clean):
    #Convert genres string to json
    for row in range(0, len(data_clean)):
        genres = json.loads(data_clean['genres'][row].replace("'", "\""))

        data_clean['genres'][row] = genres
        
    return data_clean

In [15]:
# convert to json and split features
data_clean = split_start_season(data_clean)
data_clean = split_broadcast(data_clean)
data_clean = split_statistics(data_clean)
data_clean = json_studios(data_clean)
data_clean = json_genres(data_clean)

<ipython-input-10-c6ff859d499d>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['start_season_year'][row] = year
<ipython-input-10-c6ff859d499d>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['start_season_season'][row] = season
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
<ipython-input-11-beb0346cf7cb>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['broadcast_day_of_the_week'][row] = broadcast['day_of_the_week']
<ipython-input-11-beb0346cf7cb>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['broadcast_start_time'][row] = broadcast['start_time']
<ipython-input-11-beb0346cf7cb>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['broadcast_start_time'][row] = 'NIL'
<ipython-input-12-b953b85b39a1>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['statistics_watching'][row] = statistics['status']['watching']
<ipython-input-12-b953b85b39a1>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['statistics_on_hold'][row] = statistics['status']['on_hold']
<ipython-input-12-b953b85b39a1>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['statistics_dropped'][row] = statistics['status']['dropped']
<ipython-input-12-b953b85b39a1>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['statistics_plan_to_watch'][row] = statistics['status']['plan_to_watch']
<ipython-input-12-b953b85b39a1>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['statistics_num_list_users'][row] = statistics['num_list_users']
<ipython-input-13-250b235826b3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['studios'][row] = studios
<ipython-input-14-40c4f112bd16>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean['genres'][row] = genres

---

# 3. Convert `data_clean` to `csv file`

In [16]:
data_clean.head()

,id,title,start_date,end_date,synopsis,mean,rank,popularity,num_list_users,num_scoring_users,nsfw,media_type,status,genres,num_episodes,source,average_episode_duration,rating,studios,start_season_year,start_season_season,broadcast_day_of_the_week,broadcast_start_time,statistics_watching,statistics_completed,statistics_on_hold,statistics_dropped,statistics_plan_to_watch,statistics_num_list_users
0,95,Turn A Gundam,1999-04-09,2000-04-14,"It is the Correct Century, two millennia after...",7.71,1049,2892,40743,13338,white,tv,finished_airing,"[{'id': 1, 'name': 'Action'}, {'id': 2, 'name'...",50,original,1445,pg_13,"[{'id': 14, 'name': 'Sunrise'}, {'id': 1260, '...",1999.0,spring,friday,17:00,2735.0,16661.0,2538.0,1597.0,17292.0,40823.0
1,3665,Ginga Eiyuu Densetsu Gaiden (1999),1999-12-24,2000-07-21,Ginga Eiyuu Densetsu Gaiden (1999) is the seco...,8.07,472,4347,17849,6478,white,ova,finished_airing,"[{'id': 1, 'name': 'Action'}, {'id': 8, 'name'...",28,novel,1560,r,"[{'id': 8, 'name': 'Artland'}, {'id': 207, 'na...",1999.0,fall,NIL,NIL,814.0,8080.0,638.0,293.0,8048.0,17873.0
2,2471,Doraemon (1979),1979-04-02,2005-03-18,Nobita Nobi is a normal fourth grade student. ...,7.74,976,2553,51255,23826,white,tv,finished_airing,"[{'id': 2, 'name': 'Adventure'}, {'id': 4, 'na...",1787,manga,660,pg,"[{'id': 247, 'name': 'Shin-Ei Animation'}]",1979.0,spring,NIL,NIL,4637.0,29125.0,4569.0,7816.0,5227.0,51374.0
3,21,One Piece,1999-10-20,airing,"Gol D. Roger was known as the ""Pirate King,"" t...",8.63,66,26,1812581,1020274,white,tv,currently_airing,"[{'id': 1, 'name': 'Action'}, {'id': 2, 'name'...",0,manga,1440,pg_13,"[{'id': 18, 'name': 'Toei Animation'}]",1999.0,fall,sunday,09:30,1227452.0,0.0,234652.0,161273.0,189153.0,1812530.0
4,2397,Digimon Adventure: Bokura no War Game!,2000-03-04,2000-03-04,This movie takes place after the Adventure ser...,7.77,924,2135,70125,43599,white,movie,finished_airing,"[{'id': 2, 'name': 'Adventure'}, {'id': 4, 'na...",1,original,2460,pg,"[{'id': 18, 'name': 'Toei Animation'}]",2000.0,winter,NIL,NIL,653.0,63538.0,285.0,314.0,5432.0,70222.0

In [17]:
def export_df_to_csv(data_clean, file_path):
    new_file_path = file_path[0][:-4] + '_cleaned' + '.csv'
    data_clean.to_csv(new_file_path, index=False)

In [18]:
export_df_to_csv(data_clean, file_path)

---

# Clean and process rankings csv files

In [19]:
# 1. create a function for the handling of NaN and dropping of unused features (part 1)
# 2. Use the above functions to convert to json and split the features
# 3. convert to csv following the above method!!

# NOTE: Do this iteratively.